port: 53
logLevel: warn

upstream:
  default:
    - 8.8.8.8
    - 8.8.4.4
  mori*:
    - 8.8.8.8
    - 8.8.4.4

caching:
  maxTime: 5m

customDNS:
  mapping:
    odroid: 192.168.1.5
    odroid.mono.lan: 192.168.1.5

    bree: 192.168.1.5
    bree.mono.lan: 192.168.1.5

    pi: 192.168.1.8
    pi.mono.lan: 192.168.1.8

    trantor: 192.168.1.7
    trantor.mono.lan: 192.168.1.7

    comarca: 192.168.1.7
    comarca.mono.lan: 192.168.1.7

    alpine: 192.168.1.50
    alpine.mono.lan: 192.168.1.50

    moria: 192.168.1.182, 192.168.1.183
    moria.mono.lan: 192.168.1.182, 192.168.1.183

    edgeserver-vm1: 192.168.1.57

clientLookup:
  upstream: 192.168.1.1
  clients:
    moria:
      - 192.168.1.182
    moriw:
      - 192.168.1.183

blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt
    ads2:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
    apple:
      - |
        ocsp.apple.com
  clientGroupsBlock:
    default:
      - ads
    mori*:
      - apple

