port: 53
logLevel: warn

bootstrapDns: tcp:1.1.1.1
upstream:
  default:
    - 8.8.8.8
    - 8.8.4.4
    - tcp:1.1.1.1
  mori*:
    - 8.8.8.8
    - 8.8.4.4

caching:
  maxTime: 0m

customDNS:
  mapping:
    odroid: 10.255.255.2
    odroid.mono.lan: 10.255.255.2

    bree: 10.255.255.2
    bree.mono.lan: 10.255.255.2

    pi: 10.255.255.3
    pi.mono.lan: 10.255.255.3

    trantor: 10.255.255.7
    trantor.mono.lan: 10.255.255.7

    comarca: 10.255.255.7
    comarca.mono.lan: 10.255.255.7

    alpine: 10.255.255.50
    alpine.mono.lan: 10.255.255.50

    moria: 10.255.255.11, 10.255.255.12
    moria.mono.lan: 10.255.255.11, 10.255.255.12

    edgeserver-vm1: 10.255.255.57
    debian-k3s: 10.255.255.58

clientLookup:
  upstream: 10.255.255.1
  clients:
    moria:
      - 10.255.255.11
    moriw:
      - 10.255.255.12

blocking:
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt
    ads2:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
    apple:
      - |
        ocsp.apple.com
  clientGroupsBlock:
    default:
      - ads
    mori*:
      - apple

